spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # 하이버네이트가 실행한 sql을 보여줍니다.
        format_sql: true # 하이버네이트가 실행한 sql은 보기쉽게 formating합니다
        default_batch_fetch_size: 100 # 웬만하면 옵션 키셈


logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
